server {
    listen 80;
    server_name log.demo-labs.site;

    # Force redirect HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name log.demo-labs.site;

    # Let's Encrypt SSL Certificates (Mounted from Host)
    ssl_certificate /etc/letsencrypt/live/log.demo-labs.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/log.demo-labs.site/privkey.pem;

    # Strong SSL Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API Requests to Backend Container
    location /api/ {
        proxy_pass http://backend:8000/api/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
